backend:
  name: github
  repo: aherod/mj_resume
  commit_messages:
    create: Create {{collection}} “{{slug}}” - author[{{author-name}}]
    update: Update {{collection}} “{{slug}}” - author[{{author-name}}]
    delete: Delete {{collection}} “{{slug}}” - author[{{author-name}}]
    uploadMedia: Upload “{{path}}” - author[{{author-name}}]
    deleteMedia: Delete “{{path}}” - author[{{author-name}}]

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
- name: "personal" # Used in routes, e.g., /admin/collections/content
  label: "Personal" # Used in the UI
  folder: "content" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - {label: "Phone", name: "phone", widget: "string"}
    - {label: "Email", name: "email", widget: "string"}
    - {label: "Bio", name: "bio", widget: "markdown"}
    - {label: "LinkedIn Profile URL", name: "linkedin_url", widget: "string"}
